### ISSUE TITLE
Unable to use email or session token

### ISSUE THREAD

**Issue by 6FaNcY9** [awekrx/ChatGPT-MidJourney-prompt#4]
In config im setting email, password, session token doesn't it work without API.

> ERROR: 
`Traceback (most recent call last):
  File "/usr/share/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/share/pycharm/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/vino/Documents/AiArtly/chatgpt_midjourny.py", line 37, in <module>
    promptGenerator = PromptGenerator(config)
  File "/home/vino/Documents/AiArtly/lib/python3.10/site-packages/chatGPTMidJourneyPrompt/mjPrompt.py", line 18, in __init__
    if config["api_key"]:
KeyError: 'api_key'`

**Comment by nsonaniya2010** [comment]
Don’t remove the ‘api_key’ from the config file. That should work.
